### ISSUE TITLE
Missing `newText` definition

### ISSUE THREAD

**Issue by clembu** [LuaCATS/love2d#1]
According to https://love2d.org/wiki/love.graphics.newText there is a `love.graphics.Text` constructor that accepts a table as a second parameter, interpreting it as "colored text". It seems to work fine in Löve 11.4, yet this variant is missing from the definition file.

I would submit a PR but I don't know how the doc comments work, and I don't have the time right now to get into it, so I thought I'd report it first, before I forget.

**Comment by C3pa** [comment]
Hey @carsakiller are these still built from this repo: https://github.com/love2d-community/love-api? If so, that's the place where you can document the overload.

**Comment by carsakiller** [comment]
@C3pa what do you mean *still*? Were the definition files for love2d automatically generated somewhere?

**Comment by C3pa** [comment]
IIRC, when these were part of the Lua Language Server repository, there was a Lua script that generated these annotations from this: https://github.com/love2d-community/love-api

**Comment by carsakiller** [comment]
I used the lua-language-server's script to update the API but I don't see any mention of `newText` or `.Text`, even in https://github.com/love2d-community/love-api.

**Comment by C3pa** [comment]
Yes, you are right. I asked because I wanted to know if this function should be documented in the love-api repository first as we did before for these kinds of issues, or if we are planning to diverge from that repo and maintain the annotations ourselves (which, IMHO, sounds a bit counter-productive).

**Comment by carsakiller** [comment]
@C3pa I think correcting the community documentation makes the most sense, and we can just continue to run the script to generate these definitions.

**Comment by C3pa** [comment]
Missing documentation was merged to love-api repository. Re-running the build script should fix this issue.

**Comment by carsakiller** [comment]
I have updated the API just now, if this is still an issue, perhaps the [upstream documentation](https://github.com/love2d-community/love-api) needs a fix?

**Comment by C3pa** [comment]
The upstream definitely has the mentioned overload: https://github.com/love2d-community/love-api/blob/master/modules/graphics/Graphics.lua#L2932. Maybe there's an issue with the build script: https://github.com/LuaLS/lua-language-server/blob/master/tools/love-api.lua?

**Comment by carsakiller** [comment]
Okay, hopefully https://github.com/LuaCATS/love2d/commit/173c3f38444a27d54c4479012390cc4c7c528b29 has fixed things

**Comment by C3pa** [comment]
Looks like the missing overload is here: https://github.com/LuaCATS/love2d/commit/173c3f38444a27d54c4479012390cc4c7c528b29#diff-0425179d2060217d85572f6b7c72c316c23b6565f196a7ac46496e79533606cbR839

**Comment by carsakiller** [comment]
Awesome!
