### ISSUE TITLE
inject-field diagnostics when defining LOVE callbacks.

### ISSUE THREAD

**Issue by MikuAuahDark** [LuaCATS/love2d#2]
Cross-posted from here: LuaLS/lua-language-server#2316

Basically, with LuaLS 3.7.0, this throws a warning.

```lua
local love = require("love")

function love.load() -- Fields cannot be injected into the reference of `love` for `load`. To do so, use `---@class` for `love`. (inject-field)
end
```

I expect the `love.load` declaration to have no issues.

**Comment by JJSax** [comment]
Normally you shouldn't be requiring "love".  If you're using love2d that is implied and called for you.

Taking that require out should solve your problem.

**Comment by MikuAuahDark** [comment]
Closing the one in here in favor of the LuaLS issue.
