### ISSUE TITLE
Löve2d Image:replacePixels reporting wrong number of arguments

### ISSUE THREAD

**Issue by Trystanosaurus** [LuaCATS/love2d#3]
**How are you using the lua-language-server?**
Visual Studio Code Extension (sumneko.lua)

**Which OS are you using?**
Windows

**What is the issue affecting?**
Diagnostics/Syntax Checking

**Expected Behaviour**
This might not be the place for this issue, if not feel free to close.

With löve2d when using Image:replacePixels it's reporting wrong number of arguments if you just give one, as in the example on the love2d wiki. image:replacePixels(imagedata)

The syntax checker is expecting 3: "data", "slice" and "reloadmipmaps". However "slice" only needs to be given if applicable (which it isn't with a plain texture) and "reloadmipmaps" defaults to true if the existing image has mipmaps and false if not. I appreciate it may be out of the scope of this plugin to know if these conditions are true or not.

The website in the hover over is also linking to the wrong page, it should be https://love2d.org/wiki/(Image):replacePixels

**Actual Behaviour**
Currently putting in the exaple from the love2d wiki gives an error about the nubmer of arguments.

**Reproduction steps**
Copy example from the love2d wiki page on Image:replacePixels (https://love2d.org/wiki/(Image):replacePixels)
See error being underlined
Also click the link in the hover, it goes to a non-page. This probably affects all "image" links as the wiki says these had parenthesis added to the link to as "image" was a reserved word in the wiki.
https://love2d.org/wiki/(Image):isCompressed
https://love2d.org/wiki/(Image):isFormatLinear
and https://love2d.org/wiki/(Image):replacePixels

**Comment by carsakiller** [comment]
I have updated the API just now, if this is still an issue, perhaps the [upstream documentation](https://github.com/love2d-community/love-api) needs a fix?
